services:
  postgres:
    image: postgres:16-alpine
    container_name: nextclass-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - nextclass_pgdata:/var/lib/postgresql/data

volumes:
  nextclass_pgdata: